import struct, sys

def main():
    if len(sys.argv) < 2:
        print("usage: patch_boot.py <bootloader.bin> [--header <bootblob.h>] [--verify <elf>]")
        sys.exit(1)

    bl_path = sys.argv[1]
    with open(bl_path, 'rb') as f:
        data = bytearray(f.read())

    if len(data) != 3072:
        print(f"bootloader: expected 3072 bytes, got {len(data)}")
        sys.exit(1)

    i = 2
    header_out = None
    verify_elf = None

    while i < len(sys.argv):
        if sys.argv[i] == '--header' and i + 1 < len(sys.argv):
            header_out = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] == '--verify' and i + 1 < len(sys.argv):
            verify_elf = sys.argv[i + 1]
            i += 2
        else:
            i += 1

    if verify_elf:
        with open(verify_elf, 'rb') as f:
            elf = f.read()
        if elf[:4] != b'\x7fELF':
            print("not an ELF")
            sys.exit(1)
        e_entry = struct.unpack_from('<I', elf, 0x18)[0]
        stored = struct.unpack_from('<I', data, 0x200)[0]
        if e_entry != stored:
            print(f"entry mismatch: ELF=0x{e_entry:08X} bootblob=0x{stored:08X}")
            struct.pack_into('<I', data, 0x200, e_entry)
            with open(bl_path, 'wb') as f:
                f.write(data)
            print(f"patched entry to 0x{e_entry:08X}")
        else:
            print(f"entry 0x{e_entry:08X} ok")

    if header_out:
        with open(header_out, 'w') as f:
            f.write("// auto-generated by patch_boot.py\n")
            f.write("#ifndef BOOTBLOB_H\n#define BOOTBLOB_H\n")
            f.write(f"static const unsigned char bootblob[{len(data)}] = {{\n")
            for i in range(0, len(data), 16):
                hexes = ', '.join(f'0x{b:02X}' for b in data[i:i+16])
                f.write(f"  {hexes},\n")
            f.write("};\n")
            f.write("#endif\n")
        print(f"wrote {header_out}")

if __name__ == '__main__':
    main()
