import struct, sys, os

ECX_PATTERN = b"\xfc\xf3\xa4"


def find_dap_kern(data):
    for i in range(len(data) - 16):
        if (
            data[i : i + 2] == b"\x10\x00"
            and data[i + 6 : i + 12] == b"\x00\x10\x06\x00\x00\x00"
        ):
            return i
    return None


def find_mov_ecx(data):
    for i in range(len(data) - 7):
        if data[i] == 0xB9 and data[i + 5 : i + 8] == ECX_PATTERN:
            return i
    return None


def calc_kern_size(bin_path):
    sz = os.path.getsize(bin_path)
    sectors = (sz + 511) // 512
    return sz, sectors, sectors * 512


def gen_header(data):
    lines = ["// auto-generated by patch_boot.py\n"]
    lines.append("#ifndef BOOTBLOB_H\n#define BOOTBLOB_H\n")
    lines.append(f"static const unsigned char bootblob[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        hexes = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"  {hexes},\n")
    lines.append("};\n#endif\n")
    return "".join(lines)


def main():
    if len(sys.argv) < 2:
        print(
            "usage: patch_boot.py <bootloader.bin> [--header <h>] [--verify <elf>] [--patch <kernel.bin>]"
        )
        sys.exit(1)

    bl_path = sys.argv[1]
    header_out = None
    verify_elf = None
    patch_bin = None

    i = 2
    while i < len(sys.argv):
        if sys.argv[i] == "--header" and i + 1 < len(sys.argv):
            header_out = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] == "--verify" and i + 1 < len(sys.argv):
            verify_elf = sys.argv[i + 1]
            i += 2
        elif sys.argv[i] == "--patch" and i + 1 < len(sys.argv):
            patch_bin = sys.argv[i + 1]
            i += 2
        else:
            i += 1

    with open(bl_path, "rb") as f:
        data = bytearray(f.read())
    if len(data) != 3072:
        print(f"bootloader: expected 3072 bytes, got {len(data)}")
        sys.exit(1)

    dap_off = find_dap_kern(data)
    ecx_off = find_mov_ecx(data)
    if dap_off is None or ecx_off is None:
        print("cant find DAP_kern or mov ecx")
        sys.exit(1)

    changed = False

    if verify_elf:
        with open(verify_elf, "rb") as f:
            elf = f.read()
        if elf[:4] != b"\x7fELF":
            print("not an ELF")
            sys.exit(1)
        e_entry = struct.unpack_from("<I", elf, 0x18)[0]
        stored = struct.unpack_from("<I", data, 0x202)[0]
        if e_entry != stored:
            print(f"entry mismatch: ELF=0x{e_entry:08X} bootblob=0x{stored:08X}")
            struct.pack_into("<I", data, 0x202, e_entry)
            print(f"patched entry to 0x{e_entry:08X}")
            changed = True
        else:
            print(f"entry 0x{e_entry:08X} ok")

    if patch_bin:
        kern_sz, sectors, copy_sz = calc_kern_size(patch_bin)
        old_sectors = struct.unpack_from("<H", data, dap_off + 2)[0]
        old_ecx = struct.unpack_from("<I", data, ecx_off + 1)[0]
        print(f"kernel: {kern_sz} bytes = {sectors} sectors, copy = {copy_sz} bytes")
        if sectors != old_sectors:
            struct.pack_into("<H", data, dap_off + 2, sectors)
            print(f"dap sectors: {old_sectors} -> {sectors}")
            changed = True
        if copy_sz != old_ecx:
            struct.pack_into("<I", data, ecx_off + 1, copy_sz)
            print(f"copy size: {old_ecx} -> {copy_sz}")
            changed = True
        if not changed:
            print("no patch needed")

    if changed:
        with open(bl_path, "wb") as f:
            f.write(data)
        print(f"patched {bl_path}")

    if header_out:
        content = gen_header(data)
        existing = None
        if os.path.exists(header_out):
            with open(header_out) as f:
                existing = f.read()
        if content != existing:
            with open(header_out, "w") as f:
                f.write(content)
            print(f"wrote {header_out}")
        else:
            print(f"{header_out} unchanged")


if __name__ == "__main__":
    main()
